language: node_js
node_js:
  - 0.10
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
  - npm install bower
  - bower install
script:
  - ./node_modules/karma/bin/karma start --browsers "Firefox" --single-run
